[package]
name = "lera"
version = "0.1.0"
edition = "2024"
readme = "README.md"
license = "MIT"
repository = "https://github.com/mcsamdev/lera"
description = "An optimized pure rust linear algebra library"

[dependencies]
